### PR TITLE
Fix CMakeLists.txt

### PR DESCRIPTION
**Pull request by MaxLeb**
* Let the developer choose what kind of build if wants to do  instead of forcing in Release
* Expose Boost_INCLUDE_DIR as a PUBLIC include directory for target mstch
* Update README.md to include lines about CMAKE_BUILD_TYPE

### CODE REVIEW

**Comment by rcari** [comment]
I approve the patch, it is great. However, I think we should submit it to the mainline project to integrate in official releases rather than maintaining this on our end.

**Comment by MaxLeb** [comment]
I have a PR to the mainline project already, the same as this one

**Comment by rcari** [comment]
You should not have merged this like that. We now have diverging histories in our repo and in the mainline project...

**Comment by MaxLeb** [comment]
Ok, I guess no one is using mstch master right now so what about a reset --hard on mainline and push -f ? We are pointing to mleblanc/fixCMake in the ExternalProject_add

**Pull request merged**
